//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CN.App.DrawingMiniTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_DimAttDimPartBoltAssembly_df {
            get {
                return ((int)(this["cb_DimAttDimPartBoltAssembly_df"]));
            }
            set {
                this["cb_DimAttDimPartBoltAssembly_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormLocationX {
            get {
                return ((int)(this["FormLocationX"]));
            }
            set {
                this["FormLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormLocationY {
            get {
                return ((int)(this["FormLocationY"]));
            }
            set {
                this["FormLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290")]
        public int FormWidth_df {
            get {
                return ((int)(this["FormWidth_df"]));
            }
            set {
                this["FormWidth_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("209")]
        public int FormHeight_df {
            get {
                return ((int)(this["FormHeight_df"]));
            }
            set {
                this["FormHeight_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_DimInternalPart_df {
            get {
                return ((bool)(this["chbox_DimInternalPart_df"]));
            }
            set {
                this["chbox_DimInternalPart_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_DimClose_df {
            get {
                return ((bool)(this["chbox_DimClose_df"]));
            }
            set {
                this["chbox_DimClose_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_SecMarkAttribute_df {
            get {
                return ((int)(this["cb_SecMarkAttribute_df"]));
            }
            set {
                this["cb_SecMarkAttribute_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_SecAttribute_df {
            get {
                return ((int)(this["cb_SecAttribute_df"]));
            }
            set {
                this["cb_SecAttribute_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_SectionMarkPrefix_df {
            get {
                return ((string)(this["tb_SectionMarkPrefix_df"]));
            }
            set {
                this["tb_SectionMarkPrefix_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_SectionMarkNo_df {
            get {
                return ((string)(this["tb_SectionMarkNo_df"]));
            }
            set {
                this["tb_SectionMarkNo_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_DimInternalPartInAssembly_df {
            get {
                return ((bool)(this["chbox_DimInternalPartInAssembly_df"]));
            }
            set {
                this["chbox_DimInternalPartInAssembly_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int imcb_SelectDimRefCenEdge_df {
            get {
                return ((int)(this["imcb_SelectDimRefCenEdge_df"]));
            }
            set {
                this["imcb_SelectDimRefCenEdge_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_DimentionAttributes_df {
            get {
                return ((int)(this["cb_DimentionAttributes_df"]));
            }
            set {
                this["cb_DimentionAttributes_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int imcb_DimensionTo_df {
            get {
                return ((int)(this["imcb_DimensionTo_df"]));
            }
            set {
                this["imcb_DimensionTo_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txt_RevText_df {
            get {
                return ((string)(this["txt_RevText_df"]));
            }
            set {
                this["txt_RevText_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txt_RevisionDrawing_df {
            get {
                return ((string)(this["txt_RevisionDrawing_df"]));
            }
            set {
                this["txt_RevisionDrawing_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int cb_SelectTitleReviseText_df {
            get {
                return ((int)(this["cb_SelectTitleReviseText_df"]));
            }
            set {
                this["cb_SelectTitleReviseText_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cb_PartBoltOption_df {
            get {
                return ((int)(this["cb_PartBoltOption_df"]));
            }
            set {
                this["cb_PartBoltOption_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string tb_DimSpaceDim2Part_df {
            get {
                return ((string)(this["tb_DimSpaceDim2Part_df"]));
            }
            set {
                this["tb_DimSpaceDim2Part_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string tb_DimSpaceDim2Dim_df {
            get {
                return ((string)(this["tb_DimSpaceDim2Dim_df"]));
            }
            set {
                this["tb_DimSpaceDim2Dim_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_ClearCurrentDim_df {
            get {
                return ((bool)(this["chbox_ClearCurrentDim_df"]));
            }
            set {
                this["chbox_ClearCurrentDim_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_AddPartMark_df {
            get {
                return ((bool)(this["chbox_AddPartMark_df"]));
            }
            set {
                this["chbox_AddPartMark_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int imcb_SectionSide_df {
            get {
                return ((int)(this["imcb_SectionSide_df"]));
            }
            set {
                this["imcb_SectionSide_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chbox_SkewBolts_df {
            get {
                return ((bool)(this["chbox_SkewBolts_df"]));
            }
            set {
                this["chbox_SkewBolts_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chbox_AutoFixCutPartLength_df {
            get {
                return ((bool)(this["chbox_AutoFixCutPartLength_df"]));
            }
            set {
                this["chbox_AutoFixCutPartLength_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_AutoCreateSection_df {
            get {
                return ((bool)(this["chbox_AutoCreateSection_df"]));
            }
            set {
                this["chbox_AutoCreateSection_df"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chbox_AddLine_df {
            get {
                return ((bool)(this["chbox_AddLine_df"]));
            }
            set {
                this["chbox_AddLine_df"] = value;
            }
        }
    }
}
